# Generated by Django 3.0.4 on 2020-03-18 16:07

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
    ]


