# Generated by Django 3.0.4 on 2020-03-18 17:21

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr


def load_data(apps, schema_editor):
    Hospital = apps.get_model('hospitals', 'Hospital')
    jsonfile = 'hospitals.json'

    with open(str(jsonfile)) as datafile:
        data = json.load(datafile)

        for k, v in data.items():
            name = v.get('nazwa')
            lon = v.get('geo_lon')
            lat = v.get('geo_lat')
            location = fromstr(f'POINT({lon} {lat})', srid=4326)
            phone = v.get('telefon')
            Hospital(name=name, location=location, phone=phone).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20200318_1719'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
