# Generated by Django 3.0.4 on 2020-03-25 08:45
from django.db import migrations
import json
from django.contrib.gis.geos import fromstr


def load_data(apps, schema_editor):
    Hospital = apps.get_model('hospitals', 'Hospital')
    jsonfile = 'hospitals_tr.json'

    with open(str(jsonfile)) as datafile:
        data = json.load(datafile)

        for k, v in data.items():
            name = v.get('name')
            lon = float(v.get('lon'))
            lat = float(v.get('lat'))
            location = fromstr(f'POINT({lon} {lat})', srid=4326)
            phone = v.get('phone')
            address = v.get('address')
            Hospital(name=name, location=location, address=address, phone=phone).save()


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20200318_1721'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
